### PR TITLE
update to v0.4

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@mdbartos I'm not a maintainer, so you'll need to run `@conda-forge-admin, please rerender` in a comment to get it to update the builds to include Python3.12!

Edit: Never mind! Done!

**Comment by Zeitsperre** [comment]
Once tests pass, this should be ready to merge!

**Comment by mdbartos** [comment]
Great, should I merge #14 first?

**Comment by Zeitsperre** [comment]
@mdbartos 

You can definitely merge v0.3.5 first, but I would suggest just fixing two things there:

Under `about`:
home: https://github.com/mdbartos/pysheds (is missing an 's')
license: GPL-3.0-or-later

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by mdbartos** [comment]
> @mdbartos
> 
> You can definitely merge v0.3.5 first, but I would suggest just fixing two things there:
> 
> Under `about`: home: https://github.com/mdbartos/pysheds (is missing an 's') license: GPL-3.0-or-later

Thanks, can you make the changes in that PR?

**Comment by Zeitsperre** [comment]
@conda-forge-admin, please rerender

**Comment by Zeitsperre** [comment]
@mdbartos

We're about there. I just needed to solve a few small complications from the rerendering. Would you want to extend maintenance rights to me here? It'll make the next time much easier for me.

More info: https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-add-user-username

Edit: This is good to merge!

**Review by mdbartos — APPROVED** [review]

**Pull request merged**
